version: '3.8'

services:
  mtproxy:
    build: ./mtproxy
    container_name: free-telegram-mtproxy
    network_mode: host
    environment:
      - SECRET=${MTPROXY_SECRET}
    command: ["-u", "nobody", "-p", "8443", "-S", "${MTPROXY_SECRET}", "--aes-pwd", "/opt/mtproxy/proxy-secret", "/opt/mtproxy/proxy-multi.conf", "-M", "1"]
    restart: unless-stopped

  nginx:
    image: ghcr.io/safe-stream/free-telegram.link-nginx:latest
    container_name: free-telegram-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./nginx/html/config.js:/usr/share/nginx/html/config.js:ro
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: free-telegram-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped
